name: Build vicalloy/mlc-llm-rk3588:local-id  # 定义 GitHub Actions 工作流程的名称

on:  # 指定触发工作流程的条件
  workflow_dispatch:  # 手动触发工作流程
    inputs:  # 定义手动触发时需要提供的输入参数
      model:  # 输入参数 model
        description: 'ex: Llama-2-7b-chat-hf-q4f16_1'  # 描述输入参数 model 的用途
      model-local-id:  # 输入参数 model-local-id
        description: 'ex: FlagAlpha-Llama2-Chinese-7b-Chat-q4f16_1'  # 描述输入参数 model-local-id 的用途

jobs:  # 定义作业
  build:  # 作业名称

    runs-on: ubuntu-latest  # 指定在最新的 Ubuntu 环境中运行作业

    steps:  # 定义作业的步骤
      - name: Set up QEMU  # 设置 QEMU
        uses: docker/setup-qemu-action@v2  # 使用 docker/setup-qemu-action@v2 GitHub Action

      - name: Set up Docker Buildx  # 设置 Docker Buildx
        uses: docker/setup-buildx-action@v2  # 使用 docker/setup-buildx-action@v2 GitHub Action

      - name: Login to DockerHub  # 登录到 DockerHub
        uses: docker/login-action@v1  # 使用 docker/login-action@v1 GitHub Action
        with:  # 提供登录所需的凭据
          username: ${{ secrets.DOCKERHUB_USERNAME }}  # DockerHub 用户名，从 GitHub Secrets 获取
          password: ${{ secrets.DOCKERHUB_TOKEN }}  # DockerHub 密码，从 GitHub Secrets 获取

      - name: Build and push  # 构建并推送 Docker 镜像
        uses: docker/build-push-action@v4  # 使用 docker/build-push-action@v4 GitHub Action
        env:  # 设置环境变量
          DOCKER_BUILDKIT: "1"  # 启用 Docker BuildKit
        with:  # 提供构建和推送所需的参数
          build-args: |  # 设置构建参数
            MODEL=${{ github.event.inputs.model }}  # 使用手动触发时提供的 model 参数
            MODEL_LOCAL_ID=${{ github.event.inputs.model-local-id }}  # 使用手动触发时提供的 model-local-id 参数
          file: mlc-llm-rk3588/Dockerfile  # 指定 Dockerfile 的路径
          push: true  # 构建完成后推送镜像
          platforms: linux/arm64  # 指定目标平台
          tags: vicalloy/mlc-llm-rk3588:${{ github.event.inputs.model-local-id }}  # 指定镜像的标签，使用手动触发时提供的 model-local-id 参数
